"""Emoji data — the bundled Unicode and CLDR data behind the picker, and the font rule.

Numbered Steps, Stamps & Emoji PRD Section 4.2 and implementation decision 2 (option A):
``resources/emoji/emoji.json``, generated by ``scripts/build_emoji_data.py``, holds every
fully qualified emoji of the nine categories with its name, group, subgroup, keywords, and
whether it takes a skin-tone modifier; the file is read once and cached. This module also
applies and strips the Fitzpatrick modifiers (Section 4.7) and names the platform's colour
emoji font (decision 4, option B: nothing is bundled; None when no such font is installed).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from enum import Enum
from pathlib import Path

from PyQt6.QtGui import QFontDatabase

from snapmock.core.theme_manager import RESOURCES_DIR

EMOJI_DATA_FILE = RESOURCES_DIR / "emoji" / "emoji.json"
ZERO_WIDTH_JOINER = "‍"
VARIATION_SELECTOR_16 = "️"
DEFAULT_EMOJI_SIZE = 48.0
EMOJI_SIZE_MIN = 16.0
EMOJI_SIZE_MAX = 256.0

PREFERRED_EMOJI_FAMILIES: tuple[str, ...] = (
    "Noto Color Emoji",
    "Segoe UI Emoji",
    "Apple Color Emoji",
    "Twemoji",
    "JoyPixels",
)
"""Section 4.7's platform fonts first, then any family whose name contains "emoji"."""


class SkinTone(Enum):
    """The six choices of PRD 4.2: the default yellow and the five Fitzpatrick tones."""

    DEFAULT = "default"
    LIGHT = "light"
    MEDIUM_LIGHT = "medium_light"
    MEDIUM = "medium"
    MEDIUM_DARK = "medium_dark"
    DARK = "dark"


SKIN_TONE_MODIFIERS: dict[SkinTone, str] = {
    SkinTone.LIGHT: "\U0001f3fb",
    SkinTone.MEDIUM_LIGHT: "\U0001f3fc",
    SkinTone.MEDIUM: "\U0001f3fd",
    SkinTone.MEDIUM_DARK: "\U0001f3fe",
    SkinTone.DARK: "\U0001f3ff",
}
_MODIFIER_CHARS = set(SKIN_TONE_MODIFIERS.values())
_MODIFIER_TONES = {v: k for k, v in SKIN_TONE_MODIFIERS.items()}

SKIN_TONE_SWATCHES: dict[SkinTone, str] = {
    SkinTone.DEFAULT: "#FFCC22",
    SkinTone.LIGHT: "#F7DECE",
    SkinTone.MEDIUM_LIGHT: "#F3D2A2",
    SkinTone.MEDIUM: "#D5AB88",
    SkinTone.MEDIUM_DARK: "#AF7E57",
    SkinTone.DARK: "#7C533E",
}
"""The swatch colours of the six skin-tone choices (the bar and the picker)."""


@dataclass(frozen=True)
class EmojiInfo:
    """One emoji of the bundled data (PRD 4.2)."""

    char: str
    name: str
    group: str
    subgroup: str
    keywords: tuple[str, ...]
    skin_tones: bool
    tone_slots: tuple[int, ...] = (0,)
    """Which zero-width-joiner components take the modifier (Unicode's RGI sequences)."""


def strip_skin_tone(chars: str) -> str:
    """*chars* without any Fitzpatrick modifier; the base emoji of a toned sequence."""
    return "".join(c for c in chars if c not in _MODIFIER_CHARS)


def skin_tone_of(chars: str) -> SkinTone:
    """The tone a sequence carries, DEFAULT when it carries none."""
    for c in chars:
        tone = _MODIFIER_TONES.get(c)
        if tone is not None:
            return tone
    return SkinTone.DEFAULT


def apply_skin_tone(chars: str, tone: SkinTone, slots: tuple[int, ...] = (0,)) -> str:
    """*chars* with *tone* applied to the components named by *slots* (Unicode TR51).

    *slots* are indices into the zero-width-joiner components; the modifier follows each
    component's first code point, replacing the emoji presentation selector when one is
    present. A tone of DEFAULT strips every modifier. The data's ``tone_slots`` say which
    components Unicode's sequences tone (both people of "people holding hands", never the
    handshake between them); a single emoji is slot 0.
    """
    base = strip_skin_tone(chars)
    if tone is SkinTone.DEFAULT:
        return base
    modifier = SKIN_TONE_MODIFIERS[tone]
    parts = base.split(ZERO_WIDTH_JOINER)
    toned: list[str] = []
    for index, part in enumerate(parts):
        if not part or index not in slots:
            toned.append(part)
            continue
        head, tail = part[0], part[1:]
        if tail.startswith(VARIATION_SELECTOR_16):
            tail = tail[1:]
        toned.append(head + modifier + tail)
    return ZERO_WIDTH_JOINER.join(toned)


class EmojiData:
    """The bundled emoji, loaded once (PRD 4.2)."""

    def __init__(self, path: Path | None = None) -> None:
        self._path = path if path is not None else EMOJI_DATA_FILE
        self._loaded = False
        self._groups: list[str] = []
        self._emoji: list[EmojiInfo] = []
        self._by_char: dict[str, EmojiInfo] = {}
        self._emoji_version = ""
        self._cldr_version = ""

    def _ensure_loaded(self) -> None:
        if self._loaded:
            return
        self._loaded = True
        try:
            data = json.loads(self._path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return
        if not isinstance(data, dict):
            return
        self._emoji_version = str(data.get("emoji_version", ""))
        self._cldr_version = str(data.get("cldr_version", ""))
        self._groups = [str(g) for g in data.get("groups", [])]
        for raw in data.get("emoji", []):
            if not isinstance(raw, dict) or not raw.get("char"):
                continue
            info = EmojiInfo(
                char=str(raw["char"]),
                name=str(raw.get("name", "")),
                group=str(raw.get("group", "")),
                subgroup=str(raw.get("subgroup", "")),
                keywords=tuple(str(k) for k in raw.get("keywords", [])),
                skin_tones=bool(raw.get("skin_tones", False)),
                tone_slots=tuple(int(s) for s in raw.get("tone_slots", [])) or (0,),
            )
            self._emoji.append(info)
            self._by_char[info.char] = info

    @property
    def emoji_version(self) -> str:
        self._ensure_loaded()
        return self._emoji_version

    @property
    def cldr_version(self) -> str:
        self._ensure_loaded()
        return self._cldr_version

    def groups(self) -> list[str]:
        """The nine categories of PRD 4.2, in the Unicode order."""
        self._ensure_loaded()
        return list(self._groups)

    def all(self) -> list[EmojiInfo]:
        self._ensure_loaded()
        return list(self._emoji)

    def in_group(self, group: str) -> list[EmojiInfo]:
        self._ensure_loaded()
        return [e for e in self._emoji if e.group == group]

    def lookup(self, chars: str) -> EmojiInfo | None:
        """The entry for *chars*, a toned or untoned sequence; None when unknown."""
        self._ensure_loaded()
        info = self._by_char.get(chars)
        if info is None:
            info = self._by_char.get(strip_skin_tone(chars))
        if info is None:
            bare = strip_skin_tone(chars).replace(VARIATION_SELECTOR_16, "")
            info = self._by_char.get(bare) or self._by_char.get(bare + VARIATION_SELECTOR_16)
        return info

    def toned(self, chars: str, tone: SkinTone) -> str:
        """*chars* with *tone* applied where its entry says; unchanged for an emoji that
        takes no tone."""
        info = self.lookup(chars)
        if info is None or not info.skin_tones:
            return strip_skin_tone(chars) if tone is SkinTone.DEFAULT else chars
        return apply_skin_tone(chars, tone, info.tone_slots)

    def name_of(self, chars: str) -> str:
        """The entry's name, or an empty string for an unknown sequence."""
        info = self.lookup(chars)
        return info.name if info is not None else ""

    def search(self, query: str) -> list[EmojiInfo]:
        """The emoji whose name or keywords contain every word of *query* (PRD 4.2)."""
        self._ensure_loaded()
        words = [w for w in query.casefold().split() if w]
        if not words:
            return list(self._emoji)
        found: list[EmojiInfo] = []
        for info in self._emoji:
            haystack = " ".join([info.name, *info.keywords]).casefold()
            if all(w in haystack for w in words):
                found.append(info)
        return found


_default: EmojiData | None = None


def emoji_data() -> EmojiData:
    """The application's bundled emoji data."""
    global _default
    if _default is None:
        _default = EmojiData()
    return _default


def set_emoji_data(data: EmojiData | None) -> None:
    """Replace the application's data (tests)."""
    global _default
    _default = data


def emoji_font_family(families: list[str] | None = None) -> str | None:
    """The installed colour emoji family, or None (decision 4, option B).

    Section 4.7's platform fonts are preferred in order; failing those, any family whose
    name contains "emoji". *families* replaces the font database's list (tests).
    """
    installed = families if families is not None else list(QFontDatabase.families())
    by_fold = {f.casefold(): f for f in installed}
    for preferred in PREFERRED_EMOJI_FAMILIES:
        found = by_fold.get(preferred.casefold())
        if found is not None:
            return found
    for family in installed:
        if "emoji" in family.casefold():
            return family
    return None
